import type { Metadata } from 'next';
import { Space_Grotesk as SpaceGrotesk } from 'next/font/google';
import { Footer } from '../components/Footer';
import AppProvider from '../providers/AppProvider';

import './globals.css';

const spaceGrotesk = SpaceGrotesk({
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false,
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppProvider>
        <body className={`${spaceGrotesk.className} ${spaceGrotesk.variable} `}>
          {children}
          <Footer />
        </body>
      </AppProvider>
    </html>
  );
}
